name: Build for GNU/Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-linux-onefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build onefile
        run: |
          pyinstaller --onefile --noconsole main.py

      - name: Copy assets and saves to dist
        run: |
          mkdir -p dist/assets
          mkdir -p dist/saves
          cp -r assets/ dist/assets/
          cp -r saves/ dist/saves/

      - name: Upload onefile build artifact
        uses: actions/upload-artifact@v4
        with:
          name: onefile-build-linux
          path: dist

  build-linux-debug-onefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build onefile with console enabled
        run: |
          pyinstaller --onefile main.py

      - name: Copy assets and saves to dist
        run: |
          mkdir -p dist/assets
          mkdir -p dist/saves
          cp -r assets/ dist/assets/
          cp -r saves/ dist/saves/

      - name: Upload onefile build artifact
        uses: actions/upload-artifact@v4
        with:
          name: onefile-build-linux-debug
          path: dist

  build-linux-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build folder
        run: |
          pyinstaller --noconsole main.py

      - name: Copy assets and saves to dist
        run: |
          mkdir -p dist/main/assets
          mkdir -p dist/main/saves
          cp -r assets/ dist/main/assets/
          cp -r saves/ dist/main/saves/

      - name: Upload onefile build artifact
        uses: actions/upload-artifact@v4
        with:
          name: folder-build-linux
          path: dist
    
  build-linux-debug-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build folder with console enabled
        run: |
          pyinstaller main.py

      - name: Copy assets and saves to dist
        run: |
          mkdir -p dist/main/assets
          mkdir -p dist/main/saves
          cp -r assets/ dist/main/assets/
          cp -r saves/ dist/main/saves/

      - name: Upload onefile build artifact
        uses: actions/upload-artifact@v4
        with:
          name: folder-build-linux-debug
          path: dist
